//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int ID { get; set; }
        public string UploadedBy { get; set; }
        public string FileName { get; set; }
        public string RandomName { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public int ContentLength { get; set; }
        public string ContentType { get; set; }
    }
}
