//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeblogPost
    {
        public WeblogPost()
        {
            this.WeblogComments = new HashSet<WeblogComment>();
        }
    
        public int ID { get; set; }
        public System.DateTime PostDateTime { get; set; }
        public string Writer { get; set; }
        public string Title { get; set; }
        public string PostContent { get; set; }
    
        public virtual ICollection<WeblogComment> WeblogComments { get; set; }
    }
}
